const { client } = require("./src/application/app");
const { MaretHandler } = require("./src/bot/maret");
const { animeHandler } = require("./src/bot/anime");
const { cgptHandler } = require("./src/bot/cgpt");
const { hinaAdzimHandler } = require("./src/bot/hina-adzim");
const { menuHandler } = require("./src/bot/menu");
const { pwnedHandler } = require("./src/bot/pwned");
const { quranHandler } = require("./src/bot/quran");
const { stickerHandler } = require("./src/bot/sticker");
menuHandler();
hinaAdzimHandler();
animeHandler();
cgptHandler();
pwnedHandler();
stickerHandler();
quranHandler();
MaretHandler();
client.initialize();
